#!/bin/bash

#SBATCH --job-name backup
#SBATCH --cpus-per-task 1
#SBATCH --output slurm.log.txt
#SBATCH --nice=1

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${script_dir}/bash_header"

printf "[ %s: Running backup script %s ]\n" "$(date)" "${0}"

OPTIND=1
while getopts "c:b:f:g:G:p:" opt; do
    case "${opt}" in
        c)  config_file="${OPTARG}"
            printf "   config_file: %s\n" "${config_file}"
            ;;
        b)  backup_logfile="${OPTARG}"
            printf "backup_logfile: %s\n" "${backup_logfile}"
            ;;
        f)  forget_logfile="${OPTARG}"
            printf "forget_logfile: %s\n" "${forget_logfile}"
            ;;
        g)  gen_logfile="${OPTARG}"
            printf "   gen_logfile: %s\n" "${gen_logfile}"
            ;;
        G)  gen_output="${OPTARG}"
            printf "    gen_output: %s\n" "${gen_output}"
            ;;
        p)  profile_file="${OPTARG}"
            printf "  profile_file: %s\n" "${profile_file}"
            ;;
        :)  printf "Option -%s requires an argument.\n" "${OPTARG}" >&2
            exit 1
            ;;
        \?) printf "Invalid option: -%s\n" "${OPTARG}" >&2
            exit 1
            ;;
    esac
done
shift "$((OPTIND-1))"

# obnam version
printf "[ %s: Obnam version %s ]\n" "$(date)" "$(obnam --version)"

# profile obnam
export OBNAM_PROFILE="${profile_file}"

# run backup on ricebkp
printf "[ %s: Running backup ]\n" "$(date)"
obnam --no-default-configs --config="$config_file" \
    --log="$backup_logfile" --checkpoint=100G backup

# forget old snapshots
printf "[ %s: Running forget ]\n" "$(date)"
obnam --no-default-configs --config="$config_file" \
    --log="$forget_logfile" forget

# check generations
printf "[ %s: Listing generations ]\n" "$(date)"
obnam --no-default-configs --config="$config_file" \
    --log="$gen_logfile" generations &> "$gen_output"

printf "[ %s: Done ]\n" "$(date)"

exit 0
